name: Client Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test with Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install
      - run: cd client && yarn install
      - run: cd client && yarn test
